development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: <%= ENV['PRIVATE_PUB_TOKEN'] %>
  signature_expiration: 3600 # one hour
